SELECT TABLE_SCHEMA as [schema], TABLE_NAME as name
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = CASE @schema WHEN '' THEN TABLE_SCHEMA ELSE @schema END AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME
